services:

  traefik:
    networks:
      - web-public
    ports:
      - "80:80"
      - "443:443"
    deploy:
      update_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      placement:
        constraints:
          - node.role==manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=888" # required by swarm but not used.
        - "traefik.http.routers.traefik.rule=Host(`traefik.meestermac.nl`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=traefik-auth"
        - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$/YOo3Rmu$$PghUpCZjLx9AVvjGj9g5n/"
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certificates:/certificates
    configs:
      - source: traefik
        target: /etc/traefik/traefik.yml

  mariadb:
    networks:
      - web-public
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
    deploy:
      placement:
        constraints:
          - node.role==manager
    volumes:
      - database_data:/var/lib/mysql
      - database_custom_conf:/etc/mysql/conf.d
      - database_shared:/shared

  ssh:
    # We use an SSH image so we can securely tunnel into the Docker network with 
    # tools like Sequel Pro, TablePlus, Sequel Ace, etc.
    # Learn more how to secure your tunnel here: https://github.com/serversideup/docker-ssh
    image: serversideup/docker-ssh
    ports:
      - target: 2222
        published: 2222
        mode: host
    environment:
      # Change the keys below to your own keys 
      AUTHORIZED_KEYS: >
        "# Start Keys
         ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfgNMxLGfpMq4pdX/EDxlps2h1q2A1S83Yub8ng+TvGrNWnNHZRpA26IMlGw6ZCJv4iLxJETgWEklVrdlrqMSpaCdOfkRdT0Mhsv36SDE0mXOzPS3YZV3KxcIwolXYOk+vsp9SqwMxC3HRwUnv2yg/BmG7NZQWR7NAOiE3Y0XhQR14Mj2EJ3wuEob/CEvyZ0tOndbwcgUHWUMKENKvZDpVc40yAbQKNcyfNAKwq6Q911G3f9rArtb5A8ovmmobkCrMv/JXPnOYKpUJr+ozOlldVSm1s2KIW2kI8VdYX7a+m9CIzYoeHt82y5MUg7q0V5dpVZPR9q6oJexcI0kdS6w+7zYsqpoRka/pTMWVRCLfRLkz286IE04uJKl+Dow/7DFQrD/GsJeOAdD/HOHaIORSO/8nLMjkHfXOVTcKeOmmSYQPzOCLL/yvr/0GVuIBofgdeVth3nvqKH3bTeYvzv5BNQPz8FC0LMhQaTitcES1wapDrt57lmkOpTWf50EqRgE= Sanne@MBP-van-Sanne.home
         # End Keys"
      # Be sure to configure the allowed IP addresses too
      ALLOWED_IPS: "AllowUsers *@127.0.0.1"
    volumes:
      - tunnel_ssh_host_keys:/etc/ssh/ssh_host_keys
    networks:
      - web-public

  php:
    image: ${DEPLOYMENT_IMAGE_PHP} # 👈 Be sure to change this to your own image
    networks:
      - web-public
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
    environment:
      PHP_POOL_NAME: "my-php-app"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.my-php-app.rule=${TRAEFIK_HOST_RULE}"
        - "traefik.http.routers.my-php-app.entrypoints=websecure"
        - "traefik.http.routers.my-php-app.tls=true"
        - "traefik.http.routers.my-php-app.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.my-php-app.loadbalancer.server.port=8080"
        - "traefik.http.services.my-php-app.loadbalancer.server.scheme=http"
        # Health check
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.path=/ping"
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.interval=100ms"
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.timeout=75ms"
        - "traefik.http.services.my-php-app.loadbalancer.healthcheck.scheme=http"

configs:
  traefik:
    name: "traefik.yml"
    file: ./.infrastructure/conf/traefik/prod/traefik.yml

volumes:
  certificates:
  database_data:
  database_custom_conf:
  database_shared:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
  tunnel_ssh_host_keys:

networks:
  web-public:
