# Allow self-signed certificates
serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    network: web-public
    exposedbydefault: false
    swarmMode: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

accessLog: { }
log:
  level: WARN

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  letsencryptresolver:
    acme:
      email: "help@meestermac.nl"
      storage: "/certificates/acme.json"
      httpChallenge:
        entryPoint: web
